# Generated by Django 2.1.7 on 2019-08-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_favouriterecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecord',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='likerecord',
            old_name='user',
            new_name='profile',
        ),
    ]
