# Generated by Django 2.1.7 on 2019-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='是否为精选'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
