# Generated by Django 2.1.7 on 2019-08-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190801_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='init_address',
            field=models.URLField(blank=True, null=True, verbose_name='原文地址'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_init',
            field=models.BooleanField(default=True, verbose_name='是否原创'),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_replay',
            field=models.BooleanField(default=True, verbose_name='是否开启留言'),
        ),
    ]
