# Generated by Django 2.1.7 on 2019-04-10 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountOfReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
                ('reading_date', models.DateField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '每篇阅读量统计',
                'verbose_name_plural': '每篇阅读量统计',
            },
        ),
        migrations.AlterModelOptions(
            name='readcount',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
    ]
