# Generated by Django 2.1.7 on 2019-04-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_auto_20190410_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountofreading',
            name='read_num',
            field=models.IntegerField(default=1),
        ),
    ]
