# Generated by Django 2.1.7 on 2019-08-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190802_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.TextField(default='暂无介绍', verbose_name='个人简介'),
        ),
    ]
