# Generated by Django 2.1.7 on 2019-08-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190802_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.CharField(default='正在思考中......', max_length=100, verbose_name='座右铭'),
        ),
    ]
